twitter:
  user: shokai

slack:
  channel: "#general"
  token: "your-slackbot-token"
  username: "Twitter"
  icon_emoji: ":baby_chick:" # Overrides icon_url
  icon_url: "http://lorempixel.com/48/48"

words:
  - "shokai.org"
  - "橋本商会"
  - "github.com/shokai"
  - "shokai.github"

ignore:
  users:
    - bot
    - shokai_twit
    - shokai_bot
    - shokai_log
    - end_0606_shokai
    - kirakira
    - rurourafale
    - YADAYOOOOOO
    - aine0120
    - K_T_Hotel_Annex
    - sho1nco
    - koyoshokai
  words:
    - shokai_bot
    - shopping.yahoo
    - キラキラ商会
    - kirakira
    - ビリケン
